server:
  port: 8081
spring:
  application:
    name: user-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092 #${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 0               # сколько раз повторить отправку
      properties:
        enable.idempotence: true   # включаем идемпотентность (чтобы не было дублей)
        request.timeout.ms: 2000       # ждём 3 секунды ответа от брокера
        delivery.timeout.ms: 3000     # максимум ждём 10 секунд доставки
        linger.ms: 0                   # сразу отправляем
        max.in.flight.requests.per.connection: 1 # для идемпотентности
      acks: 1
    admin:
      # Включает KafkaAdmin для создания топиков
      auto-create: true
    topic:
      name: user-events
      partitions: 3
      replication-factor: 1
