spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
      auto-startup: true
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "dev.folomkin.shared.dto"
      spring.json.value.default.type: "dev.folomkin.shared.dto.UserDto"
server:
  port: 8082
